application: myapplication
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.[^/]*)/(.*\.(html|jpg|png|gif|ico|js|css))
  static_files: \1/static/\2
  upload: (.[^/]*)/static/(.*\.(html|jpg|png|gif|ico|js|css))

- url: /(.[^/]*)/
  static_files: \1/static/index.html
  upload: (.[^/]*)/static/index.html

- url: /(.[^/]*)/(.*)\.appcache
  static_files: \1/static/\2.appcache
  upload: (.[^/]*)/static/(.*)\.appcache
  mime_type: text/cache-manifest
